### ISSUE TITLE
Support for GPU gathers without the Aluminum MPI-CUDA backend

### ISSUE THREAD

**Issue by timmoon10** [llnl/Elemental#54]
When I build without the Aluminum MPI-CUDA backend, GPU gathers fail at runtime since NCCL doesn't support gather. I see several options:
- Write a fallback gather implementation that synchronously copies GPU data to the CPU, calls MPI_Gather, and copies back to the GPU.
- Make MPI-CUDA a requirement when building Hydrogen with CUDA support. If MPI-CUDA is too unstable, NCCL can take precedence for the operations it supports.
- How hard is it to make invalid type/device/collective combinations a compile-time error? I'm thinking we could make the default template implementation include a failed static assert.
- Change the LBANN build script to build with MPI-CUDA by default.

**Comment by benson31** [comment]
I'm pretending your "itemize" is actually "enumerate":

1. This is already supported if `Hydrogen_AVOID_CUDA_AWARE_MPI=ON` or if the CMake couldn't detect CUDA-aware MPI.
2. NCCL already does take precedence. I'm reluctant to make MPI-CUDA default since there are some core sematics issues that need to be resolved. And it probably violates the MPI standard a lot.
3. The issue with doing this is the way Hydrogen instantiates the MPI wrappers (inherited from Elemental). That is, you define some horrid `MPI_PROTO(T)` macro and call it for each `T` that you know of. I could change this but I'm sort on time (Read: I desperately want to change this. Complain louder to the guy who controls the money so it becomes more important.).
4. Sure, do this one.

**Comment by benson31** [comment]
Thanks! It's a huge pain and someone should really go clean all that up. Also, Include What You Use never killed anyone. Just sayin'.

**Comment by timmoon10** [comment]
2, 3, 4 are fair points. For 1, can we get that behavior even if CUDA-aware MPI is being used? Right now I just get an error message like:
```
Process 0 caught error message:
Gather: Bad device/type combination.
```

**Comment by benson31** [comment]
That's a bigger error. I think that will be fixed in my `fix-gcc-8` branch. I'm trying to merge that today.

**Comment by benson31** [comment]
Should this be closed now?
